### ISSUE TITLE
NVDLA Build and Simulation

### ISSUE THREAD

**Issue by haroonrl** [nvdla/hw#80]
I was wondering to know whether NVDLA build is completed or not, here is the build log attached, please help me figure out

[build.log](https://github.com/nvdla/hw/files/1572106/build.log)

**Comment by jwise** [comment]
It looks like source generation completed, but since you haven't set up a path to VCS, the VCS build did not complete.  You can see the message: `files are generated under /home/harry/hw-master/outdir/nv_small/vmod/nvdla/top`, but: `checkcompile : Compile FAILED (Warnings=0, Errors=0, ExecutableReady=0)` is the message to indicate that VCS did not run successfully.
